last_block_height: 1 # last block height for sync, first block height is 1
sync_interval_per_block: 5 # 5 seconds
indexer_uuid: "8bc5d30c-1ccc-460c-adcc-508608b0c188" # this uuid store in database for get last changes indexer in database

pactus:
  rpc: ""

dbs: # currently support mysql, postgresql, mongodb
  - name: "mysql 1"
    type: "sql" # types: sql and nosql
    engine: "mysql" # engines: mysql, psql, mongodb, mariadb
    uri: "mysql://admin:password123@localhost:3306/mydatabase"

  - name: "postgres 1"
    type: "sql"
    engine: "psql"
    uri: "postgresql://admin:password123@localhost:5432/mydatabase"

  - name: "mariadb 1"
    type: "sql"
    engine: "mariadb"
    uri: "mysql://admin:password123@localhost:3306/mydatabase"

  - name: "mongodb 1"
    type: "nosql"
    engine: "mongodb"
    uri: "mongodb://admin:password123@localhost:27017/mydatabase"
    database: "foobar"

logging:
  debug: true
  handler: 0
  enable_caller: true
  sentry_dsn: "dsn"